services:
  - type: web
    name: bakery-ai
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn server:app --workers 2 --threads 4 --timeout 120 --log-file -
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: FLASK_ENV
        value: production
