services:
  - type: web
    name: bakery-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
